// A++ Programming Language
// Author: OXOP, and probably more cuz of PR and stuff

#ifndef CODE_GENERATOR_HPP
#define CODE_GENERATOR_HPP

#include "ast.hpp"
#include "error_handler.hpp"
#include <string>
#include <sstream>

enum class TargetLang { NATIVE, CPP, PYTHON, CSHARP, JS };

class CodeGenerator {
public:
    CodeGenerator(TargetLang target, ErrorHandler& err)
        : target_(target), err_(err), indentLevel_(0) {}

    std::string generate(ASTNodePtr root) {
        switch (target_) {
            case TargetLang::CPP:    return generateCpp(root);
            case TargetLang::PYTHON: return generatePython(root);
            case TargetLang::CSHARP: return generateCSharp(root);
            case TargetLang::JS:     return generateJS(root);
            default:                 return generateCpp(root);
        }
    }

private:
    TargetLang    target_;
    ErrorHandler& err_;
    int           indentLevel_;
    std::ostringstream out_;

    std::string indent() { return std::string(indentLevel_ * 4, ' '); }

    // ── C++ backend ─────────────────────────────────────────────────────────
    std::string generateCpp(ASTNodePtr root) {
        out_.str(""); out_.clear();
        out_ << "// Generated by A++ compiler (target: C++)\n";
        out_ << "#include <iostream>\n#include <string>\n#include <vector>\n";
        out_ << "#include <map>\n#include <cmath>\nusing namespace std;\n\n";
        emitCpp(root);
        return out_.str();
    }

    void emitCpp(ASTNodePtr n) {
        if (!n) return;
        switch (n->type) {
            case NodeType::PROGRAM:
            case NodeType::BLOCK:
                for (auto& c : n->children) emitCpp(c);
                break;
            case NodeType::PRINT_STMT:
                out_ << indent() << "cout << ";
                if (!n->children.empty()) emitCpp(n->children[0]);
                out_ << " << endl;\n";
                break;
            case NodeType::VAR_DECL:
                out_ << indent() << "auto " << n->value << " = ";
                if (!n->children.empty()) emitCpp(n->children.back());
                out_ << ";\n";
                break;
            case NodeType::FUNC_DECL:
                out_ << indent() << "auto " << n->value << "(";
                out_ << ") {\n";
                indentLevel_++;
                for (auto& c : n->children) emitCpp(c);
                indentLevel_--;
                out_ << indent() << "}\n\n";
                break;
            case NodeType::RETURN_STMT:
                out_ << indent() << "return ";
                if (!n->children.empty()) emitCpp(n->children[0]);
                out_ << ";\n";
                break;
            case NodeType::IF_STMT:
                out_ << indent() << "if (";
                if (!n->children.empty()) emitCpp(n->children[0]);
                out_ << ") {\n";
                indentLevel_++;
                if (n->children.size() > 1) emitCpp(n->children[1]);
                indentLevel_--;
                out_ << indent() << "}\n";
                if (n->children.size() > 2) {
                    out_ << indent() << "else {\n";
                    indentLevel_++;
                    emitCpp(n->children[2]);
                    indentLevel_--;
                    out_ << indent() << "}\n";
                }
                break;
            case NodeType::WHILE_STMT:
                out_ << indent() << "while (";
                if (!n->children.empty()) emitCpp(n->children[0]);
                out_ << ") {\n";
                indentLevel_++;
                if (n->children.size() > 1) emitCpp(n->children[1]);
                indentLevel_--;
                out_ << indent() << "}\n";
                break;
            case NodeType::BINARY_EXPR:
                if (n->children.size() >= 2) {
                    emitCpp(n->children[0]);
                    out_ << " " << n->value << " ";
                    emitCpp(n->children[1]);
                }
                break;
            case NodeType::INT_LITERAL:
            case NodeType::FLOAT_LITERAL:
                out_ << n->value;
                break;
            case NodeType::STRING_LITERAL:
                out_ << "\"" << n->value << "\"";
                break;
            case NodeType::BOOL_LITERAL:
                out_ << n->value;
                break;
            case NodeType::IDENTIFIER:
                out_ << n->value;
                break;
            case NodeType::CALL_EXPR:
                out_ << n->value << "(";
                for (size_t i = 0; i < n->children.size(); i++) {
                    if (i > 0) out_ << ", ";
                    emitCpp(n->children[i]);
                }
                out_ << ")";
                break;
            default:
                for (auto& c : n->children) emitCpp(c);
                break;
        }
    }

    // ── Python backend ───────────────────────────────────────────────────────
    std::string generatePython(ASTNodePtr root) {
        out_.str(""); out_.clear();
        out_ << "# Generated by A++ compiler (target: Python)\n\n";
        emitPython(root);
        return out_.str();
    }

    void emitPython(ASTNodePtr n) {
        if (!n) return;
        switch (n->type) {
            case NodeType::PROGRAM:
            case NodeType::BLOCK:
                for (auto& c : n->children) emitPython(c);
                break;
            case NodeType::PRINT_STMT:
                out_ << indent() << "print(";
                if (!n->children.empty()) emitPython(n->children[0]);
                out_ << ")\n";
                break;
            case NodeType::VAR_DECL:
                out_ << indent() << n->value << " = ";
                if (!n->children.empty()) emitPython(n->children.back());
                out_ << "\n";
                break;
            case NodeType::FUNC_DECL:
                out_ << indent() << "def " << n->value << "():\n";
                indentLevel_++;
                for (auto& c : n->children) emitPython(c);
                if (n->children.empty()) out_ << indent() << "pass\n";
                indentLevel_--;
                out_ << "\n";
                break;
            case NodeType::RETURN_STMT:
                out_ << indent() << "return ";
                if (!n->children.empty()) emitPython(n->children[0]);
                out_ << "\n";
                break;
            case NodeType::IF_STMT:
                out_ << indent() << "if ";
                if (!n->children.empty()) emitPython(n->children[0]);
                out_ << ":\n";
                indentLevel_++;
                if (n->children.size() > 1) emitPython(n->children[1]);
                indentLevel_--;
                if (n->children.size() > 2) {
                    out_ << indent() << "else:\n";
                    indentLevel_++;
                    emitPython(n->children[2]);
                    indentLevel_--;
                }
                break;
            case NodeType::WHILE_STMT:
                out_ << indent() << "while ";
                if (!n->children.empty()) emitPython(n->children[0]);
                out_ << ":\n";
                indentLevel_++;
                if (n->children.size() > 1) emitPython(n->children[1]);
                indentLevel_--;
                break;
            case NodeType::BINARY_EXPR:
                if (n->children.size() >= 2) {
                    emitPython(n->children[0]);
                    std::string op = n->value;
                    if (op == "&&") op = "and";
                    if (op == "||") op = "or";
                    if (op == "!") op = "not";
                    out_ << " " << op << " ";
                    emitPython(n->children[1]);
                }
                break;
            case NodeType::INT_LITERAL:
            case NodeType::FLOAT_LITERAL:
                out_ << n->value;
                break;
            case NodeType::STRING_LITERAL:
                out_ << "\"" << n->value << "\"";
                break;
            case NodeType::BOOL_LITERAL:
                out_ << (n->value == "true" ? "True" : "False");
                break;
            case NodeType::IDENTIFIER:
                out_ << n->value;
                break;
            case NodeType::CALL_EXPR:
                out_ << n->value << "(";
                for (size_t i = 0; i < n->children.size(); i++) {
                    if (i > 0) out_ << ", ";
                    emitPython(n->children[i]);
                }
                out_ << ")";
                break;
            default:
                for (auto& c : n->children) emitPython(c);
                break;
        }
    }

    // ── C# backend ───────────────────────────────────────────────────────────
    std::string generateCSharp(ASTNodePtr root) {
        out_.str(""); out_.clear();
        out_ << "// Generated by A++ compiler (target: C#)\n";
        out_ << "using System;\nusing System.Collections.Generic;\n\n";
        out_ << "class Program {\n";
        out_ << "    static void Main(string[] args) {\n";
        indentLevel_ = 2;
        emitCSharp(root);
        out_ << "    }\n}\n";
        return out_.str();
    }

    void emitCSharp(ASTNodePtr n) {
        if (!n) return;
        switch (n->type) {
            case NodeType::PROGRAM:
            case NodeType::BLOCK:
                for (auto& c : n->children) emitCSharp(c);
                break;
            case NodeType::PRINT_STMT:
                out_ << indent() << "Console.WriteLine(";
                if (!n->children.empty()) emitCSharp(n->children[0]);
                out_ << ");\n";
                break;
            case NodeType::VAR_DECL:
                out_ << indent() << "var " << n->value << " = ";
                if (!n->children.empty()) emitCSharp(n->children.back());
                out_ << ";\n";
                break;
            case NodeType::FUNC_DECL:
                out_ << indent() << "static void " << n->value << "() {\n";
                indentLevel_++;
                for (auto& c : n->children) emitCSharp(c);
                indentLevel_--;
                out_ << indent() << "}\n\n";
                break;
            case NodeType::RETURN_STMT:
                out_ << indent() << "return ";
                if (!n->children.empty()) emitCSharp(n->children[0]);
                out_ << ";\n";
                break;
            case NodeType::IF_STMT:
                out_ << indent() << "if (";
                if (!n->children.empty()) emitCSharp(n->children[0]);
                out_ << ") {\n";
                indentLevel_++;
                if (n->children.size() > 1) emitCSharp(n->children[1]);
                indentLevel_--;
                out_ << indent() << "}\n";
                if (n->children.size() > 2) {
                    out_ << indent() << "else {\n";
                    indentLevel_++;
                    emitCSharp(n->children[2]);
                    indentLevel_--;
                    out_ << indent() << "}\n";
                }
                break;
            case NodeType::BINARY_EXPR:
                if (n->children.size() >= 2) {
                    emitCSharp(n->children[0]);
                    out_ << " " << n->value << " ";
                    emitCSharp(n->children[1]);
                }
                break;
            case NodeType::INT_LITERAL:
            case NodeType::FLOAT_LITERAL:
                out_ << n->value;
                break;
            case NodeType::STRING_LITERAL:
                out_ << "\"" << n->value << "\"";
                break;
            case NodeType::BOOL_LITERAL:
                out_ << n->value;
                break;
            case NodeType::IDENTIFIER:
                out_ << n->value;
                break;
            default:
                for (auto& c : n->children) emitCSharp(c);
                break;
        }
    }

    // ── JavaScript backend ───────────────────────────────────────────────────
    std::string generateJS(ASTNodePtr root) {
        out_.str(""); out_.clear();
        out_ << "// Generated by A++ compiler (target: JavaScript)\n\n";
        emitJS(root);
        return out_.str();
    }

    void emitJS(ASTNodePtr n) {
        if (!n) return;
        switch (n->type) {
            case NodeType::PROGRAM:
            case NodeType::BLOCK:
                for (auto& c : n->children) emitJS(c);
                break;
            case NodeType::PRINT_STMT:
                out_ << indent() << "console.log(";
                if (!n->children.empty()) emitJS(n->children[0]);
                out_ << ");\n";
                break;
            case NodeType::VAR_DECL:
                out_ << indent() << "let " << n->value << " = ";
                if (!n->children.empty()) emitJS(n->children.back());
                out_ << ";\n";
                break;
            case NodeType::CONST_DECL:
                out_ << indent() << "const " << n->value << " = ";
                if (!n->children.empty()) emitJS(n->children.back());
                out_ << ";\n";
                break;
            case NodeType::FUNC_DECL:
                out_ << indent() << "function " << n->value << "() {\n";
                indentLevel_++;
                for (auto& c : n->children) emitJS(c);
                indentLevel_--;
                out_ << indent() << "}\n\n";
                break;
            case NodeType::RETURN_STMT:
                out_ << indent() << "return ";
                if (!n->children.empty()) emitJS(n->children[0]);
                out_ << ";\n";
                break;
            case NodeType::BINARY_EXPR:
                if (n->children.size() >= 2) {
                    emitJS(n->children[0]);
                    out_ << " " << n->value << " ";
                    emitJS(n->children[1]);
                }
                break;
            case NodeType::INT_LITERAL:
            case NodeType::FLOAT_LITERAL:
                out_ << n->value;
                break;
            case NodeType::STRING_LITERAL:
                out_ << "`" << n->value << "`";
                break;
            case NodeType::BOOL_LITERAL:
                out_ << n->value;
                break;
            case NodeType::IDENTIFIER:
                out_ << n->value;
                break;
            default:
                for (auto& c : n->children) emitJS(c);
                break;
        }
    }
};

#endif // CODE_GENERATOR_HPP
